### PR TITLE
Solving my first Issue

### PR DESCRIPTION
**Pull request by agamswaroop619**
Improved response for Premium Discord Bot service. Added response.html which views the website with given characteristics

Key changes -
-> Changed the former router file, payment_routes.py, that handles premium transactions. to accommodate with my response.html
-> Added response.html that delivers the final message depending on transition passed or failed

### CODE REVIEW

**Comment by agamswaroop619** [comment]
Screenshot 2023-06-06 at 8 16 43 PM
Screenshot 2023-06-06 at 8 15 29 PM
Here are the screenshots of said response.html

**Comment by agamswaroop619** [comment]
Key changes -
-> Changed the former router file, payment_routes.py, that handles premium transactions. to accommodate with my response.html
-> Added response.html that delivers the final message depending on transition passed or failed

**Review by deadaf — CHANGES_REQUESTED** [review]
Hey @agamswaroop619 , This looks fantastic and I must say much better than the previous PR.
The text is displayed in the middle of the screen so I suppose it won't be a problem, but still can you add screenshots of how this will look on mobile devices as well?

**Comment by deadaf** [comment]
on a related note, for future references, I suggest mentioning the issue you are addressing in the PR description as well.

**Comment by agamswaroop619** [comment]
image
image
These are the screenshots of mobile versions using Chrome's Dev tools

**Comment by deadaf** [comment]
Thanks @agamswaroop619 !

**Pull request merged**
