### PR TITLE
grammer phix

### PR DESCRIPTION
**Pull request by Shadowaf**

### CODE REVIEW

**Review by swayyed — CHANGES_REQUESTED** [review]
"Claim a tag whose owner has left the server."

**Comment by ShashankKumarSaxena** [comment]
"Claim a tag if the tag owner has left the server"

**Comment by swayyed** [comment]
> "Claim a tag if the tag owner has left the server"

sir it all means the same, the former looked elegant.

**Comment by ShashankKumarSaxena** [comment]
> > "Claim a tag if the tag owner has left the server"
> 
> sir it all means the same, the former looked elegant.

kon padhta hai bc, maine galti se dekh liya tha

**Pull request merged**
